[2023-03-23 09:11:00,574] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact')
[2023-03-23 09:11:00,574] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact')
[2023-03-23 09:11:00,574] root - INFO - Data Ingestion config: DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/Shivan118/Main-Branching/main/TourismData.csv', tgz_download_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-23-09-10-58\\tgz_data', raw_data_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-23-09-10-58\\raw_data', ingested_train_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-23-09-10-58\\ingested_data\\train', ingested_test_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-23-09-10-58\\ingested_data\\test')
[2023-03-23 09:11:00,574] root - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
[2023-03-23 09:11:00,574] root - INFO - Downloading file from :[https://raw.githubusercontent.com/Shivan118/Main-Branching/main/TourismData.csv] into :[C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\traveling\artifact\data_ingestion\2023-03-23-09-10-58\tgz_data\TourismData.csv]
[2023-03-23 09:11:39,336] root - ERROR - 
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\pipeline\pipeline.py ] at 
        try block line number: [36] and exception block line number: [39] 
        error message: [
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\pipeline\pipeline.py ] at 
        try block line number: [27] and exception block line number: [29] 
        error message: [
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\components\data_ingestion.py ] at 
        try block line number: [125] and exception block line number: [129] 
        error message: [
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\components\data_ingestion.py ] at 
        try block line number: [45] and exception block line number: [50] 
        error message: [<urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>]
        ]
        ]
        ]
        
