[2023-03-24 08:01:51,339] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact')
[2023-03-24 08:01:51,345] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact')
[2023-03-24 08:01:51,345] root - INFO - Data Ingestion config: DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/Shivan118/Main-Branching/main/TourismData.csv', tgz_download_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-24-08-01-48\\tgz_data', raw_data_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-24-08-01-48\\raw_data', ingested_train_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-24-08-01-48\\ingested_data\\train', ingested_test_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\config_data_ingestion\\traveling\\artifact\\data_ingestion\\2023-03-24-08-01-48\\ingested_data\\test')
[2023-03-24 08:01:51,347] root - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
[2023-03-24 08:01:51,347] root - INFO - Downloading file from :[https://raw.githubusercontent.com/Shivan118/Main-Branching/main/TourismData.csv] into :[C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\traveling\artifact\data_ingestion\2023-03-24-08-01-48\tgz_data\TourismData.csv]
[2023-03-24 08:02:33,485] root - ERROR - 
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\pipeline\pipeline.py ] at 
        try block line number: [36] and exception block line number: [39] 
        error message: [
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\pipeline\pipeline.py ] at 
        try block line number: [27] and exception block line number: [29] 
        error message: [
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\components\data_ingestion.py ] at 
        try block line number: [125] and exception block line number: [129] 
        error message: [
        Error occured in script: 
        [ C:\Users\Sumeet Maheshwari\Desktop\config_data_ingestion\travelling\components\data_ingestion.py ] at 
        try block line number: [45] and exception block line number: [50] 
        error message: [<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>]
        ]
        ]
        ]
        
